export const JUSTIFICATIVAS_SIGILO = [
  { value: "lai-23-i",      label: "Art. 23, I — Defesa e soberania nacionais (LAI 12.527/2011)" },
  { value: "lai-23-ii",     label: "Art. 23, II — Política monetária ou cambial (LAI 12.527/2011)" },
  { value: "lai-23-iii",    label: "Art. 23, III — Operações militares em andamento (LAI 12.527/2011)" },
  { value: "lai-23-iv",     label: "Art. 23, IV — Risco à vida, segurança ou saúde (LAI 12.527/2011)" },
  { value: "lai-23-v",      label: "Art. 23, V — Projetos de pesquisa e desenvolvimento (LAI 12.527/2011)" },
  { value: "lai-23-vi",     label: "Art. 23, VI — Risco à estabilidade econômico-financeira (LAI 12.527/2011)" },
  { value: "lai-23-vii",    label: "Art. 23, VII — Inteligência e contrainteligência (LAI 12.527/2011)" },
  { value: "lai-23-viii",   label: "Art. 23, VIII — Informações de países estrangeiros (LAI 12.527/2011)" },
  { value: "pad",           label: "Processo Administrativo Disciplinar em andamento" },
  { value: "licit-14133",   label: "Art. 94 Lei 14.133/2021 — Sigilo de proposta em licitação" },
  { value: "cpc-189",       label: "Art. 189 CPC — Segredo de justiça em processo judicial" },
  { value: "ctn-198",       label: "Art. 198 CTN — Sigilo fiscal" },
  { value: "lc-105",        label: "LC 105/2001 — Sigilo de operações financeiras (bancário)" },
  { value: "lgpd-sensivel", label: "Art. 11 LGPD (Lei 13.709/2018) — Dados pessoais sensíveis" },
  { value: "lgpd-pessoal",  label: "Art. 7º LGPD (Lei 13.709/2018) — Dados pessoais identificáveis" },
  { value: "saude",         label: "Procedimento médico ou informação de saúde do servidor" },
  { value: "negoc",         label: "Negociação coletiva ou acordo trabalhista em andamento" },
  { value: "inquerito",     label: "Investigação policial ou inquérito em curso" },
];
